# Generated by Django 5.0.6 on 2024-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_ended',
            field=models.DateTimeField(verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_started',
            field=models.DateTimeField(verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_to_end',
            field=models.DateTimeField(verbose_name='дата окончания'),
        ),
    ]
